exclude:
- README.md
- DEV.md

title: "Logan Hood"
description: "Personal website and technology blog"
url: "https://www.loganhood.com"
author: "Logan Hood"

feed:
  posts_limit: 100

plugins:
  - jekyll-feed
